version: '3.4'

services:
  nosqldata:
    image: mongo

  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest

  catalog.api:
    image: ${DOCKER_REGISTRY:-bookcase}/catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - sqldata
      - identity.api

  identity.api:
    image: ${DOCKER_REGISTRY:-bookcase}/identity.api
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile
    depends_on:
      - sqldata

  shelves.api:
    image: ${DOCKER_REGISTRY:-bookcase}/shelves.api
    build:
      context: .
      dockerfile: Services/Shelf/Shelves.API/Dockerfile
    depends_on:
      - nosqldata
      - identity.api
